name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.stability }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.2, 7.4, 8.0]
        symfony: [4.4.*, 5.2.*]
        stability: [hightest]
        include:
          - php: 7.2
            stability: lowest
            symfony: '*'
          - php: 8.0
            stability: highest
            symfony: '@dev'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex dev-main

      - name: Set minimum-stability to dev
        run: composer config minimum-stability dev
        if: ${{ matrix.symfony == '@dev' }}

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.stability }}
          composer-options: --prefer-dist
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Run tests
        run: bin/phpunit -v

      - name: Run phpspec
        run: bin/phpspec run --format=pretty

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: xdebug

      - name: Install dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: --prefer-dist

      - name: Run code coverage
        run: bin/phpunit -v --coverage-text

  composer-validate:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Validate composer.json
        run: composer validate --strict --no-check-lock
